[package]
name = "minion-lib"
version = "0.1.0"
authors = ["derek"]
edition = "2018"

[dependencies]
hyper = "0.12.21"
futures = "0.1.21"
futures-cpupool = { version = "0.1.6", optional = true }
serde_json = "1.0"
pretty_env_logger = "0.2.0"